{
  config,
  pkgs,
  paths,
  ...
}: {
  #Hypridle config
  services.hypridle = {
    enable = true;
    settings = {
      general = {
        lock_cmd = "hyprlock";
        on_unlock_cmd = "notify-send 'salus anculhez'";
      };

      listener = [
        {
          timeout = 230;
          on-timeout = "brightnessctl -s set 10";
          on-resume = "brightnessctl -r";
        }
        {
          timeout = 300;
          on-timeout = "loginctl lock-session";
        }
        {
          timeout = 600;
          on-timeout = "systemctl suspend";
        }
      ];
    };
  };

  #Hyprlock config
  xdg.configFile."hypr/hyprlock.conf".text = ''
    # Sourcing colors generated by wallust
    $dScripts = $HOME/.config/hypr/scripts

    general {
        grace = 1
        fractional_scaling = 2
        immediate_render = true
    }

    background {
        monitor =
        path = ${paths.nixosAsciiWallpaper}

        color = rgb(0,0,0) # color will be rendered initially until path is available

        blur_size = 3
        blur_passes = 2 # 0 disables blurring
        noise = 0.0117
        contrast = 1.3000 # Vibrant!!!
        brightness = 0.8000
        vibrancy = 0.2100
        vibrancy_darkness = 0.0
    }

    # Date
    label {
        monitor =
        text = cmd[update:18000000] echo "<b> "$(date +'%A, %-d %B')" </b>"
        color = rgb(878787)
        font_size = 16
        font_family = Victor Mono Bold Italic
        position = 0, -120
        halign = center
        valign = center
    }

    # Hour-Time
    label {
        monitor =
        text = cmd[update:1000] echo "$(date +"%H")"
        color = rgb(878787)
        font_size = 200
        font_family = JetBrainsMono Nerd Font ExtraBold
        position = 0, -60
        halign = center
        valign = top
    }

    # Minute-Time
    label {
        monitor =
        text = cmd[update:1000] echo "$(date +"%M")"
        color = rgb(797979)
        font_size = 200
        font_family = JetBrainsMono Nerd Font ExtraBold
        position = 0, -340
        halign = center
        valign = top
    }

    # Seconds-Time
    label {
        monitor =
        text = cmd[update:1000] echo "$(date +"%S")"
        color = rgb(6C6C6C)
        font_size = 35
        font_family = JetBrainsMono Nerd Font ExtraBold
        position = 0, -350
        halign = center
        valign = top
    }


    # USER
    label {
        monitor =
        text =   $USER
        color = rgb(878787)
        font_size = 24
        font_family = Victor Mono Bold Oblique
        position = 0, 220
        halign = center
        valign = bottom
    }

    # INPUT FIELD
    input-field {
        monitor =
        size = 200, 60
        outline_thickness = 2
        dots_size = 0.2
        dots_spacing = 0.2
        dots_center = true
        outer_color = rgb(6C6C6C)
        inner_color = rgba(255, 255, 255, 0.1)
        capslock_color = rgb(255,255,255)
        font_color = rgb(878787)
        fade_on_empty = false
        font_family = Victor Mono Bold Oblique
        placeholder_text = <i><span foreground="##ffffff99">🔒 Type Password</span></i>
        hide_input = false
        position = 0, 100
        halign = center
        valign = bottom
    }

    # Keyboard LAYOUT
    label {
        monitor =
        text = $LAYOUT
        color = rgb(878787)
        font_size = 10
        font_family = Victor Mono Bold Oblique
        position = 0, 70
        halign = center
        valign = bottom
    }

    # weather
    label {
        monitor =
        text = cmd[update:3600000] [ -f "$HOME/.cache/.weather_cache" ] && cat "$HOME/.cache/.weather_cache"
        color = rgb(878787)
        font_size = 16
        font_family = Victor Mono Bold Oblique
        position = 50, 0
        halign = left
        valign = bottom
    }
  '';
}

